const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = __dirname;
const GAME_PATH = path.join(ROOT, 'game.js');
const GENERATED_DIR = path.join(ROOT, 'assets', 'spritesheets', 'enemies', 'generated');
const REGENERATED_DIR = path.join(ROOT, 'assets', 'spritesheets', 'enemies', 'regenerated');
const MANIFEST_PATH = path.join(GENERATED_DIR, 'manifest.json');
const FRAME_SIZE = 256;

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

async function buildEnemyAssets() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(`Missing enemy sprite manifest at ${MANIFEST_PATH}. Run node gen_sprite_sheets.js first.`);
  }

  const manifest = readJson(MANIFEST_PATH);
  const b64Map = {};
  const defs = {};

  for (const id of Object.keys(manifest)) {
    const meta = manifest[id];
    let pngPath = path.join(GENERATED_DIR, `${id}.png`);

    if (!fs.existsSync(pngPath)) {
      console.warn(`Maintained generated sheet missing for ${id}, falling back to regenerated source.`);
      pngPath = path.join(REGENERATED_DIR, `${id}.png`);
    }

    if (!fs.existsSync(pngPath)) {
      throw new Error(`Missing sprite sheet: ${pngPath}`);
    }

    const targetW = meta.cols * FRAME_SIZE;
    const targetH = meta.rows * FRAME_SIZE;

    console.log(`Processing ${id}: ${pngPath} -> ${targetW}x${targetH}`);

    const buffer = await sharp(pngPath)
      .resize(targetW, targetH, { fit: 'fill', kernel: 'lanczos3' })
      .png({ compressionLevel: 9 })
      .toBuffer();

    b64Map[id] = `data:image/png;base64,${buffer.toString('base64')}`;
    defs[id] = {
      cols: meta.cols,
      rows: meta.rows,
      fps: meta.fps,
      anims: meta.anims
    };

    console.log(`${id}: ${meta.width}x${meta.height} -> ${targetW}x${targetH}`);
  }

  return { b64Map, defs };
}

function generateEnemyAssetsFile(b64Map, defs) {
  return `// Generated by gen_enemy_assets.js\n\n` +
    `var ENEMY_SPRITE_B64 = ${JSON.stringify(b64Map, null, 2)};\n\n` +
    `var ENEMY_SPRITE_DEFS = ${JSON.stringify(defs, null, 2)};\n`;
}

async function main() {
  const { b64Map, defs } = await buildEnemyAssets();
  const fileContent = generateEnemyAssetsFile(b64Map, defs);
  fs.writeFileSync(path.join(ROOT, 'enemy_assets.js'), fileContent);
  console.log(`Updated enemy sprite assets in enemy_assets.js`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
